# cls: 
# dataset:
_target_: experimenting.dataset.core.SadCore
name: timecount_dhp19
root: J:\datasets\DVS\mmd\time_count_dataset
config_name: 'config_test.yaml'
batch_size: ${batch_size}
# D:\Dataset\DVS\dhp19\time_count_dataset
# /mnt/d/Dataset/DVS/dhp19/time_count_dataset
# data_dir: ${dataset.root}/frames
# joints_dir: ${dataset.root}/labels

test_subjects: [0]
cams: [0]
test_cams: [0]
n_channels: 1
n_joints: 13
partition: cross-subject
#! Potential Problems here! Unit: m
avg_torso_length: 50
