augmentation_train:
  type: center_crop_normalize
  apply:
    aug1:
      _target_: albumentations.CenterCrop
      params:
        height: 224
        width: 224
        p: 1.0
    aug2:
      _target_: albumentations.Normalize
      params:
        mean: 0.0074
        std: 0.0553
    aug3:
      _target_: albumentations.pytorch.ToTensorV2

augmentation_test:
  type: center_crop_normalize
  apply:
    aug1:
      _target_: albumentations.CenterCrop
      params:
        height: 224
        width: 224
        p: 1.0
    aug2:
      _target_: albumentations.Normalize
      params:
        mean: 0.0074
        std: 0.0553
    aug3:
      _target_: albumentations.pytorch.ToTensorV2