augmentation_train:
  type: center_crop
  info:
    height: 256
    width: 256
  apply:
    aug1:
        _target_: albumentations.CenterCrop
        params:
          height: 256
          width: 256
          p: 1.0
    aug2:
        _target_: albumentations.pytorch.ToTensorV2

augmentation_test:
  type: center_crop
  info:
    height: 256
    width: 256
  apply:
    aug1:
        _target_: albumentations.CenterCrop
        params:
          height: 256
          width: 256
          p: 1.0
    aug2:
        _target_: albumentations.pytorch.ToTensorV2
