augmentation_train:
  type: no_aug
  apply:
    aug1:
      _target_: albumentations.pytorch.ToTensorV2

augmentation_test:
  type: no_aug
  apply:
    aug1:
      _target_: albumentations.pytorch.ToTensorV2

      
          

